version: '3.8'

services:
  nginx:
    build:
      context: ./requirements/NGINX
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - wp-network
    restart: always

  wordpress:
    build:
      context: ./requirements/WordPress
    volumes:
      - wp-data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    networks:
      - wp-network
    restart: always

  mariadb:
    build:
      context: ./requirements/MariaDB
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - wp-network
    restart: always

volumes:
  db-data:
  wp-data:

networks:
  wp-network: