networks:
  app-network:
    name: app-network
    driver: bridge

volumes:
  mariadb_data:
    driver: local 
    driver_opts:
      type: none
      o: bind
      device: ${MARIADB_PATH}

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${WORDPRESS_PATH}

services:

  mariadb:
    image: mariadb
    build: ./requirements/mariadb
    container_name: mariadb
    env_file: .env
    
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app-network

    restart: unless-stopped

  wordpress:
    image: wordpress
    build: ./requirements/wordpress
    container_name: wordpress
    env_file: .env

    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    networks:
      - app-network

    restart: unless-stopped

  nginx:
    image: nginx
    build: ./requirements/nginx
    container_name: nginx
    env_file: .env
    
    depends_on:
      - mariadb
    ports:
      - "443:443"

    restart: unless-stopped

