# networks:
#   app-network:
#     name: app-network
#     driver: bridge

volumes:
  mariadb_data:
    driver: local 
    driver_opts:
      type: none
      o: bind
      device: ${MARIADB_PATH}

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
      
    # restart: unless-stopped
    # networks:
    #   - app-network
  